name: Java CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'jdk'
        architecture: x64
        server-id: github
        server-username: ${{ github.actor }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite: true

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download dependencies and build
      run: mvn -B clean package

    - name: Run unit tests
      run: mvn test
